### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dungjava** [ilovefuud/Titanium#5] opened 2022-05-30 01:41 UTC
[03:37:07 ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper.titanium.packetevents.injector.PaperChannelInjector.ADD_LISTENER_METHOD" is null initializing Titanium v1.1.2-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "io.github.retrooper.titanium.packetevents.injector.PaperChannelInjector.ADD_LISTENER_METHOD" is null
        at io.github.retrooper.titanium.packetevents.injector.PaperChannelInjector.inject(PaperChannelInjector.java:75) ~[titanium-1.1.2-SNAPSHOT.jar:?]
        at io.github.retrooper.titanium.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:111) ~[titanium-1.1.2-SNAPSHOT.jar:?]
        at me.jaden.titanium.Titanium.onLoad(Titanium.java:32) ~[titanium-1.1.2-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[pearl-1.18.2.jar:git-Pearl-"7664b7c"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:291) ~[pearl-1.18.2.jar:git-Pearl-"7664b7c"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1166) ~[pearl-1.18.2.jar:git-Pearl-"7664b7c"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pearl-1.18.2.jar:git-Pearl-"7664b7c"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ilovefuud** [comment] 2022-05-30 15:16
Plugin doesn’t work on 1.18 right now. Honestly, you don’t need an anticrasher if you’re using 1.18 as paper already fixes them for you. If you still want to use my plugin I’ll let you know when the issue is fixed as there are still benefits to using my plugin.

**Comment by ilovefuud** [comment] 2022-06-01 19:03
fixed in [a7b3f98](https://github.com/ilovefuud/Titanium/commit/a7b3f984acbe6c795d112476b8170fb39d5dd77a) @Dungjava

**Closed by ilovefuud** 2022-06-01 19:03 UTC
